apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edureka-jenkins-problem1
  annotations:
    github.com/project-slug: thiagofdso/edureka-jenkins-problem1
    jenkins.io/job-full-name: "default:edureka-jenkins-problem1"
spec:
  type: webapi
  lifecycle: development
  owner: guests
