apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: edureka-jenkins-problem1
  annotations:
    'jenkins.io/job-full-name': thiagofdso-edureka/edureka-jenkins-problem1
    github.com/project-slug: thiagofdso/edureka-jenkins-problem1
spec:
  type: service
  lifecycle: development
  owner: guests
